In [1]:
import pandas as pd
from pathlib import Path
pd.set_option('display.max_columns', None)

## 01

In [2]:
financial_data_01 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/01_financial_status_labels_100k.csv")

In [3]:
financial_data_01_sample = financial_data_01.sample(n=1000, random_state=42)

In [7]:
financial_data_01_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,latest_period_end,latest_available_date,financial_evidence_tier,cash,creditors_total,current_assets,debtors,employees,equity,fixed_assets,net_assets_liabilities,net_current_assets_liabilities,profit_loss,total_assets_less_current_liabilities,negative_equity_eligible,negative_equity_flag,positive_equity_flag,working_capital_deficit_eligible,working_capital_deficit_flag,reported_loss_eligible,reported_loss_flag,creditors_cover_eligible,creditors_exceed_current_assets_flag,current_assets_cover_creditors_flag,cash_to_creditors_ratio,fixed_assets_to_disclosed_assets_ratio,debtors_to_current_assets_ratio,creditors_to_disclosed_assets_ratio,employees_per_million_disclosed_assets,cash_coverage_eligible,cash_coverage_band,cash_coverage_threshold_scope,cash_coverage_threshold_n,cash_coverage_low_threshold,cash_coverage_high_threshold,asset_intensity_eligible,asset_intensity_band,asset_intensity_threshold_scope,asset_intensity_threshold_n,asset_intensity_low_threshold,asset_intensity_high_threshold,receivables_intensity_eligible,receivables_intensity_band,receivables_intensity_threshold_scope,receivables_intensity_threshold_n,receivables_intensity_low_threshold,receivables_intensity_high_threshold,creditor_intensity_eligible,creditor_intensity_band,creditor_intensity_threshold_scope,creditor_intensity_threshold_n,creditor_intensity_low_threshold,creditor_intensity_high_threshold,employee_intensity_eligible,employee_intensity_band,employee_intensity_threshold_scope,employee_intensity_threshold_n,employee_intensity_low_threshold,employee_intensity_high_threshold
75721,11153083,LARWIN ESTATES LTD,Real Estate,MICRO ENTITY,2024-01-31,2024-10-31,T2_balance_sheet_rich,NaN,394242.0,806.0,NaN,0.0,29202.0,2032346.0,29202.0,-393436.0,NaN,1638910.0,True,False,True,True,True,False,NaN,True,True,False,NaN,0.999604,NaN,0.193907,0.000000,False,NaN,NaN,NaN,NaN,NaN,True,High,sector_account_category,7816.0,0.774839,0.984552,False,NaN,NaN,NaN,NaN,NaN,True,Medium,sector_account_category,10669.0,0.122423,0.875577,True,Low,sector_account_category,10960.0,0.000000,3.558808
80184,13431081,EMPORIUM OF WONDERS LIMITED,Wholesale & Retail,TOTAL EXEMPTION FULL,2025-06-30,2026-03-31,T2_balance_sheet_rich,10.0,35596.0,10900.0,NaN,0.0,-24005.0,NaN,-24005.0,-24696.0,NaN,NaN,True,True,False,True,True,False,NaN,True,True,False,0.000281,NaN,NaN,3.265688,0.000000,True,Low,sector_account_category,5847.0,0.117050,0.965851,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,High,sector_account_category,5687.0,0.334458,0.934968,True,Low,sector_account_category,5585.0,5.326358,42.552965
19864,10472899,GREEN HOME ENERGY (PRIVATE) LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-03-31,2025-12-31,T2_balance_sheet_rich,NaN,602582.0,47366.0,NaN,2.0,-555216.0,NaN,-555216.0,-555216.0,NaN,-555216.0,True,True,False,True,True,False,NaN,True,True,False,NaN,NaN,NaN,12.721826,42.224380,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,High,sector_account_category,13268.0,0.255858,0.918420,True,Medium,sector_account_category,13562.0,4.940744,71.946069
76699,10800893,GROWTH GORILLA LTD,"Technology, legal & professional",TOTAL EXEMPTION FULL,2025-03-31,2026-01-31,T2_balance_sheet_rich,144672.0,164749.0,257349.0,112677.0,9.0,92946.0,NaN,92946.0,92600.0,NaN,93336.0,True,False,True,True,False,False,NaN,True,False,True,0.878136,NaN,0.437837,0.640177,34.971964,True,Medium,sector_account_category,7773.0,0.278549,1.881974,False,NaN,NaN,NaN,NaN,NaN,True,Medium,sector_account_category,6699.0,0.189215,0.729518,True,Medium,sector_account_category,7395.0,0.246925,0.875528,True,Medium,sector_account_category,7285.0,4.322864,45.273881
92991,11377376,VAQUOI LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-05-31,2026-02-28,T2_balance_sheet_rich,NaN,5902.0,NaN,NaN,0.0,-5902.0,NaN,-5902.0,-5902.0,NaN,-5902.0,True,True,False,True,True,False,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN

In [5]:
financial_data_01_sample.to_csv("../output/samples/01_financial_status_labels_100k_sample.csv", index=False)

## 02

In [8]:
financial_data_02 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/02_financial_scale_labels_100k.csv")

In [9]:
financial_data_02_sample = financial_data_02.sample(n=1000, random_state=42)

In [10]:
financial_data_02_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,latest_period_end,latest_available_date,financial_evidence_tier,current_assets,fixed_assets,creditors_total,equity,employees,net_assets_liabilities,total_assets_less_current_liabilities,abs_equity_for_scale,current_assets_scale_eligible,current_assets_scale_band,current_assets_scale_threshold_scope,current_assets_scale_threshold_n,current_assets_scale_low_threshold,current_assets_scale_high_threshold,fixed_assets_scale_eligible,fixed_assets_scale_band,fixed_assets_scale_threshold_scope,fixed_assets_scale_threshold_n,fixed_assets_scale_low_threshold,fixed_assets_scale_high_threshold,creditors_scale_eligible,creditors_scale_band,creditors_scale_threshold_scope,creditors_scale_threshold_n,creditors_scale_low_threshold,creditors_scale_high_threshold,absolute_equity_scale_eligible,absolute_equity_scale_band,absolute_equity_scale_threshold_scope,absolute_equity_scale_threshold_n,absolute_equity_scale_low_threshold,absolute_equity_scale_high_threshold,employee_scale_eligible,employee_scale_band,employee_scale_threshold_scope,employee_scale_threshold_n,employee_scale_low_threshold,employee_scale_high_threshold,net_assets_scale_eligible,net_assets_scale_band,net_assets_scale_threshold_scope,net_assets_scale_threshold_n,net_assets_scale_low_threshold,net_assets_scale_high_threshold,total_assets_scale_eligible,total_assets_scale_band,total_assets_scale_threshold_scope,total_assets_scale_threshold_n,total_assets_scale_low_threshold,total_assets_scale_high_threshold,financial_scale_available_field_count
75721,11153083,LARWIN ESTATES LTD,Real Estate,MICRO ENTITY,2024-01-31,2024-10-31,T2_balance_sheet_rich,806.0,2032346.0,394242.0,29202.0,0.0,29202.0,1638910.0,29202.0,True,Low,sector_account_category,11274.0,7.895026,10.316534,True,High,sector_account_category,8322.0,11.215532,13.003492,True,High,sector_account_category,10971.0,8.547528,11.748488,True,Medium,sector_account_category,12282.0,7.937589,10.542440,True,Low,sector_account_category,11827.0,0.000000,0.693147,True,High,sector_account_category,11184.0,2.397895,10.037131,True,High,sector_account_category,11839.0,8.016779,12.222167,7
80184,13431081,EMPORIUM OF WONDERS LIMITED,Wholesale & Retail,TOTAL EXEMPTION FULL,2025-06-30,2026-03-31,T2_balance_sheet_rich,10900.0,NaN,35596.0,-24005.0,0.0,-24005.0,NaN,24005.0,True,Low,sector_account_category,5717.0,10.361855,12.637665,False,NaN,NaN,NaN,NaN,NaN,True,Medium,sector_account_category,6143.0,9.887886,11.935098,True,Medium,sector_account_category,6121.0,7.420579,11.504359,True,Low,sector_account_category,6129.0,0.693147,1.609438,True,Low,sector_account_category,5505.0,5.737858,11.751320,False,NaN,NaN,NaN,NaN,NaN,5
19864,10472899,GREEN HOME ENERGY (PRIVATE) LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-03-31,2025-12-31,T2_balance_sheet_rich,47366.0,NaN,602582.0,-555216.0,2.0,-555216.0,-555216.0,555216.0,True,Medium,sector_account_category,13771.0,8.696510,10.768632,False,NaN,NaN,NaN,NaN,NaN,True,High,sector_account_category,13661.0,8.436200,10.204888,True,High,sector_account_category,14493.0,7.868738,10.318956,True,High,sector,24199.0,0.693147,1.098612,True,Low,sector_account_category,12839.0,5.973297,10.033937,True,Low,sector_account_category,13863.0,6.999239,10.279929,6
76699,10800893,GROWTH GORILLA LTD,"Technology, legal & professional",TOTAL EXEMPTION FULL,2025-03-31,2026-01-31,T2_balance_sheet_rich,257349.0,NaN,164749.0,92946.0,9.0,92946.0,93336.0,92946.0,True,High,sector_account_category,7266.0,9.895581,11.960297,False,NaN,NaN,NaN,NaN,NaN,True,High,sector_account_category,8274.0,9.123114,11.008329,True,High,sector_account_category,8275.0,6.908755,11.041960,True,High,sector_account_category,8322.0,0.693147,1.098612,True,High,sector_account_category,6632.0,6.818374,11.271809,True,Medium,sector_account_category,6963.0,8.127759,11.572128,6
92991,11377376,VAQUOI LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-05-31,2026-02-28,T2_balance_sheet_rich,NaN,NaN,5902.0,-5902.0,0.0,-5902.0,-5902.0,5902.0,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,Medium,sector_account_category,13661.0,8.436200,10.204888,True,Medium,sector_account_category,14493.0,7.868738,10.318956,True,Low,sector,24199.0,0.693147,1.098612,True,Low,sector_account_category,12839.0,5.973297,10.033937,True,Low,sector_account_category,13863.0,6.999239,10.279929,5

In [11]:
financial_data_02_sample.to_csv("../output/samples/02_financial_scale_labels_100k_sample.csv", index=False)

## 03

In [13]:
financial_data_03 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/03_financial_change_labels.csv")

C:\Users\86132\AppData\Local\Temp\ipykernel_3020\364946345.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  financial_data_03 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/03_financial_change_labels.csv")

In [14]:
financial_data_03_sample = financial_data_03.sample(n=1000, random_state=42)

In [15]:
financial_data_03_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,period_t,period_t_plus_1,available_date_t,available_date_t_plus_1,gap_days,evidence_tier_t,evidence_tier_t_plus_1,current_assets_t,current_assets_t_plus_1,current_assets_change_eligible,current_assets_signed_log_change,current_assets_percent_change,current_assets_change_band,current_assets_change_threshold_scope,current_assets_change_threshold_n,current_assets_change_low_threshold,current_assets_change_high_threshold,fixed_assets_t,fixed_assets_t_plus_1,fixed_assets_change_eligible,fixed_assets_signed_log_change,fixed_assets_percent_change,fixed_assets_change_band,fixed_assets_change_threshold_scope,fixed_assets_change_threshold_n,fixed_assets_change_low_threshold,fixed_assets_change_high_threshold,creditors_total_t,creditors_total_t_plus_1,creditors_total_change_eligible,creditors_total_signed_log_change,creditors_total_percent_change,creditors_total_change_band,creditors_total_change_threshold_scope,creditors_total_change_threshold_n,creditors_total_change_low_threshold,creditors_total_change_high_threshold,equity_t,equity_t_plus_1,equity_change_eligible,equity_signed_log_change,equity_percent_change,equity_change_band,equity_change_threshold_scope,equity_change_threshold_n,equity_change_low_threshold,equity_change_high_threshold,net_assets_liabilities_t,net_assets_liabilities_t_plus_1,net_assets_liabilities_change_eligible,net_assets_liabilities_signed_log_change,net_assets_liabilities_percent_change,net_assets_liabilities_change_band,net_assets_liabilities_change_threshold_scope,net_assets_liabilities_change_threshold_n,net_assets_liabilities_change_low_threshold,net_assets_liabilities_change_high_threshold,cash_t,cash_t_plus_1,cash_change_eligible,cash_signed_log_change,cash_percent_change,cash_change_band,cash_change_threshold_scope,cash_change_threshold_n,cash_change_low_threshold,cash_change_high_threshold,debtors_t,debtors_t_plus_1,debtors_change_eligible,debtors_signed_log_change,debtors_percent_change,debtors_change_band,debtors_change_threshold_scope,debtors_change_threshold_n,debtors_change_low_threshold,debtors_change_high_threshold,employees_t,employees_t_plus_1,employees_change_eligible,employees_signed_log_change,employees_percent_change,employees_change_band,employees_change_threshold_scope,employees_change_threshold_n,employees_change_low_threshold,employees_change_high_threshold,total_assets_less_current_liabilities_t,total_assets_less_current_liabilities_t_plus_1,total_assets_less_current_liabilities_change_eligible,total_assets_less_current_liabilities_signed_log_change,total_assets_less_current_liabilities_percent_change,total_assets_less_current_liabilities_change_band,total_assets_less_current_liabilities_change_threshold_scope,total_assets_less_current_liabilities_change_threshold_n,total_assets_less_current_liabilities_change_low_threshold,total_assets_less_current_liabilities_change_high_threshold,change_available_field_count
64119,13955543,ALPHA UK INVESTMENTS LIMITED,Real Estate,TOTAL EXEMPTION FULL,2024-03-31,2025-03-31,2024-12-31,2026-01-31,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297499.0,385175.0,True,0.258286,0.294710,High,sector_account_category,7921.0,-0.038033,0.141550,-14466.0,-24138.0,True,-0.511959,-0.668602,Low,sector_account_category,8086.0,-0.015229,0.117307,-14466.0,-24138.0,True,-0.511959,-0.668602,Low,sector_account_category,6647.0,-0.052052,0.187852,NaN,400.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,True,0.000000,NaN,NaN,global,76322.0,0.0,0.0,105668.0,93753.0,True,-0.119637,-0.112759,Low,sector_account_category,7207.0,-0.022273,0.081042,5
68035,14390075,CR WENTWORTH PT LIMITED,"Technology, legal & professional",MICRO ENTITY,2024-09-26,2025-09-26,2025-12-31,2026-06-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,7319024.0,8446705.0,True,0.143299,0.154075,Medium,sector_account_category,11826.0,-0.242803,0.203960,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7103773.0,8020107.0,True,0.121326,0.128993,Medium,sector_account_category,11608.0,-0.169462,0.245164,215251.0,423931.0,True,0.677764,0.969473,High,sector_account_category,12622.0,-0.251333,0.241930,215251.0,423931.0,True,0.677764,0.969473,High,sector_account_category,10569.0,-0.255811,0.235162,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215251.0,426598.0,True,0.684035,0.981863,High,sector_account_category,11536.0,-0.285350,0.191123,5
53647,12765519,MYLEE'S LTD,Wholesale & Retail,TOTAL EXEMPTION FULL,2024-07-31,2025-07-31,2025-04-30,2026-04-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,159954.0,115554.0,True,-0.325146,-0.277580,Low,sector_account_category,4949.0,-0.121391,0.148947,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82810.0,58216.0,True,-0.352383,-0.296993,Low,sector_account_category,5330.0,-0.105680,0.251414,9163.0,508.0,True,-2.890590,-0.944560,Low,sector_account_category,5347.0,-0.100931,0.111431,9163.0,508.0,True,-2.890590,-0.944560,Low,sector_account_category,4738.0,-0.152195,0.185589,83827.0,49025.0,True,-0.536416,-0.415165,Low,sector_account_category,4902.0,-0.359543,0.276379,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,True,0.223144,0.333333,NaN,global,76322.0,0.0,0.0,92725.0,73270.0,True,-0.235484,-0.209814,Low,sector_account_category,4508.0,-0.176497,0.120040,7
49880,12316478,SOUTH CUMBRIAN PROPERTIES LTD,Real Estate,MICRO ENTITY,2023-11-30,2024-11-30,2024-08-31,2025-09-30,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,7583.0,11865.0,True,0.447636,0.564684,High,sector_account_category,9513.0,-0.134505,0.266623,101000.0,101000.0,True,0.000000,0.000000,High,sector,10793.0,-0.000029,0.000000,101264.0,95846.0,True,-0.054988,-0.053504,Low,sector_account_category,9167.0,-0.032524,0.122857,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,10749.0,-0.028350,0.216066,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,9240.0,-0.028697,0.229073,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,True,0.000000,NaN,NaN,global,76322.0,0.0,0.0,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,9793.0,-0.011594,0.084710,7
13810,5962404,SAINT ANDREWS PROPERTIES LIMITED,Real Estate,TOTAL EXEMPTION FULL,2023-10-31,2024-10-31,2024-07-31,2025-07-31,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,NaN,21578.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1082674.0,1082381.0,True,-0.000271,-0.000271,Low,sector_account_category,3363.0,-0.000185,0.000469,66934.0,65538.0,True,-0.021077,-0.020856,Medium,sector_account_category,7921.0,-0.038033,0.141550,173690.0,181822.0,True,0.045756,0.046819,Medium,sector_account_category,8086.0,-0.015229,0.117307,173690.0,181822.0,True,0.045756,0.046819,Medium,sector_account_category,6647.0,-0.052052,0.187852,24990.0,12593.0,True,-0.685295,-0.496078,Low,sector_account_category,7278.0,-0.342290,0.427888,NaN,8985.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,True,0.000000,0.000000,NaN,global,76322.0,0.0,0.0,1040730.0,1038421.0,True,-0.002221,-0.002219,Medium,sector_account_category,7207.0,-0.022273,0.081042,7

In [16]:
financial_data_03_sample.to_csv("../output/samples/03_financial_change_labels_sample.csv", index=False)

## 03 new

In [4]:
financial_data_03_new_path = Path(r"E:\files\Bristol\project\记录\data\finance\03_financial_change_labels.csv")

In [5]:
financial_data_03_new = pd.read_csv(financial_data_03_new_path)

C:\Users\86132\AppData\Local\Temp\ipykernel_24204\2921774310.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  financial_data_03_new = pd.read_csv(financial_data_03_new_path)

In [6]:
financial_data_03_new_sample = financial_data_03_new.sample(n=1000, random_state=42)

In [7]:
financial_data_03_new_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,period_t,period_t_plus_1,available_date_t,available_date_t_plus_1,gap_days,evidence_tier_t,evidence_tier_t_plus_1,current_assets_t,current_assets_t_plus_1,current_assets_change_eligible,current_assets_signed_log_change,current_assets_percent_change,current_assets_change_band,current_assets_change_threshold_scope,current_assets_change_threshold_n,current_assets_change_low_threshold,current_assets_change_high_threshold,fixed_assets_t,fixed_assets_t_plus_1,fixed_assets_change_eligible,fixed_assets_signed_log_change,fixed_assets_percent_change,fixed_assets_change_band,fixed_assets_change_threshold_scope,fixed_assets_change_threshold_n,fixed_assets_change_low_threshold,fixed_assets_change_high_threshold,creditors_total_t,creditors_total_t_plus_1,creditors_total_change_eligible,creditors_total_signed_log_change,creditors_total_percent_change,creditors_total_change_band,creditors_total_change_threshold_scope,creditors_total_change_threshold_n,creditors_total_change_low_threshold,creditors_total_change_high_threshold,equity_t,equity_t_plus_1,equity_change_eligible,equity_signed_log_change,equity_percent_change,equity_change_band,equity_change_threshold_scope,equity_change_threshold_n,equity_change_low_threshold,equity_change_high_threshold,net_assets_liabilities_t,net_assets_liabilities_t_plus_1,net_assets_liabilities_change_eligible,net_assets_liabilities_signed_log_change,net_assets_liabilities_percent_change,net_assets_liabilities_change_band,net_assets_liabilities_change_threshold_scope,net_assets_liabilities_change_threshold_n,net_assets_liabilities_change_low_threshold,net_assets_liabilities_change_high_threshold,net_current_assets_liabilities_t,net_current_assets_liabilities_t_plus_1,net_current_assets_liabilities_change_eligible,net_current_assets_liabilities_signed_log_change,net_current_assets_liabilities_percent_change,net_current_assets_liabilities_change_band,net_current_assets_liabilities_change_threshold_scope,net_current_assets_liabilities_change_threshold_n,net_current_assets_liabilities_change_low_threshold,net_current_assets_liabilities_change_high_threshold,cash_t,cash_t_plus_1,cash_change_eligible,cash_signed_log_change,cash_percent_change,cash_change_band,cash_change_threshold_scope,cash_change_threshold_n,cash_change_low_threshold,cash_change_high_threshold,debtors_t,debtors_t_plus_1,debtors_change_eligible,debtors_signed_log_change,debtors_percent_change,debtors_change_band,debtors_change_threshold_scope,debtors_change_threshold_n,debtors_change_low_threshold,debtors_change_high_threshold,employees_t,employees_t_plus_1,employees_change_eligible,employees_signed_log_change,employees_percent_change,employees_change_band,employees_change_threshold_scope,employees_change_threshold_n,employees_change_low_threshold,employees_change_high_threshold,profit_loss_t,profit_loss_t_plus_1,profit_loss_change_eligible,profit_loss_signed_log_change,profit_loss_percent_change,profit_loss_change_band,profit_loss_change_threshold_scope,profit_loss_change_threshold_n,profit_loss_change_low_threshold,profit_loss_change_high_threshold,total_assets_less_current_liabilities_t,total_assets_less_current_liabilities_t_plus_1,total_assets_less_current_liabilities_change_eligible,total_assets_less_current_liabilities_signed_log_change,total_assets_less_current_liabilities_percent_change,total_assets_less_current_liabilities_change_band,total_assets_less_current_liabilities_change_threshold_scope,total_assets_less_current_liabilities_change_threshold_n,total_assets_less_current_liabilities_change_low_threshold,total_assets_less_current_liabilities_change_high_threshold,change_available_field_count
64119,13955543,ALPHA UK INVESTMENTS LIMITED,Real Estate,TOTAL EXEMPTION FULL,2024-03-31,2025-03-31,2024-12-31,2026-01-31,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,297499.0,385175.0,True,0.258286,0.294710,High,sector_account_category,7921.0,-0.038033,0.141550,-14466.0,-24138.0,True,-0.511959,-0.668602,Low,sector_account_category,8086.0,-0.015229,0.117307,-14466.0,-24138.0,True,-0.511959,-0.668602,Low,sector_account_category,6647.0,-0.052052,0.187852,-297499.0,-384775.0,True,-0.257247,-0.293366,Low,sector_account_category,7898.0,-0.111294,0.091883,NaN,400.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,True,0.000000,NaN,NaN,global,76322.0,0.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105668.0,93753.0,True,-0.119637,-0.112759,Low,sector_account_category,7207.0,-0.022273,0.081042,6
68035,14390075,CR WENTWORTH PT LIMITED,"Technology, legal & professional",MICRO ENTITY,2024-09-26,2025-09-26,2025-12-31,2026-06-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,7319024.0,8446705.0,True,0.143299,0.154075,Medium,sector_account_category,11826.0,-0.242803,0.203960,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7103773.0,8020107.0,True,0.121326,0.128993,Medium,sector_account_category,11608.0,-0.169462,0.245164,215251.0,423931.0,True,0.677764,0.969473,High,sector_account_category,12622.0,-0.251333,0.241930,215251.0,423931.0,True,0.677764,0.969473,High,sector_account_category,10569.0,-0.255811,0.235162,215251.0,426598.0,True,0.684035,0.981863,High,sector_account_category,11628.0,-0.329817,0.237822,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215251.0,426598.0,True,0.684035,0.981863,High,sector_account_category,11536.0,-0.285350,0.191123,6
53647,12765519,MYLEE'S LTD,Wholesale & Retail,TOTAL EXEMPTION FULL,2024-07-31,2025-07-31,2025-04-30,2026-04-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,159954.0,115554.0,True,-0.325146,-0.277580,Low,sector_account_category,4949.0,-0.121391,0.148947,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82810.0,58216.0,True,-0.352383,-0.296993,Low,sector_account_category,5330.0,-0.105680,0.251414,9163.0,508.0,True,-2.890590,-0.944560,Low,sector_account_category,5347.0,-0.100931,0.111431,9163.0,508.0,True,-2.890590,-0.944560,Low,sector_account_category,4738.0,-0.152195,0.185589,77144.0,57338.0,True,-0.296706,-0.256741,Low,sector_account_category,5320.0,-0.275740,0.162979,83827.0,49025.0,True,-0.536416,-0.415165,Low,sector_account_category,4902.0,-0.359543,0.276379,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,True,0.223144,0.333333,NaN,global,76322.0,0.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92725.0,73270.0,True,-0.235484,-0.209814,Low,sector_account_category,4508.0,-0.176497,0.120040,8
49880,12316478,SOUTH CUMBRIAN PROPERTIES LTD,Real Estate,MICRO ENTITY,2023-11-30,2024-11-30,2024-08-31,2025-09-30,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,7583.0,11865.0,True,0.447636,0.564684,High,sector_account_category,9513.0,-0.134505,0.266623,101000.0,101000.0,True,0.000000,0.000000,High,sector,10793.0,-0.000029,0.000000,101264.0,95846.0,True,-0.054988,-0.053504,Low,sector_account_category,9167.0,-0.032524,0.122857,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,10749.0,-0.028350,0.216066,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,9240.0,-0.028697,0.229073,93681.0,83981.0,True,-0.109304,-0.103543,Low,sector_account_category,9689.0,-0.081886,0.115526,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,True,0.000000,NaN,NaN,global,76322.0,0.0,0.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7319.0,17019.0,True,0.843779,1.325318,High,sector_account_category,9793.0,-0.011594,0.084710,8
13810,5962404,SAINT ANDREWS PROPERTIES LIMITED,Real Estate,TOTAL EXEMPTION FULL,2023-10-31,2024-10-31,2024-07-31,2025-07-31,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,NaN,21578.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1082674.0,1082381.0,True,-0.000271,-0.000271,Low,sector_account_category,3363.0,-0.000185,0.000469,66934.0,65538.0,True,-0.021077,-0.020856,Medium,sector_account_category,7921.0,-0.038033,0.141550,173690.0,181822.0,True,0.045756,0.046819,Medium,sector_account_category,8086.0,-0.015229,0.117307,173690.0,181822.0,True,0.045756,0.046819,Medium,sector_account_category,6647.0,-0.052052,0.187852,-41944.0,-43960.0,True,-0.046944,-0.048064,Medium,sector_account_category,7898.0,-0.111294,0.091883,24990.0,12593.0,True,-0.685295,-0.496078,Low,sector_account_category,7278.0,-0.342290,0.427888,NaN,8985.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,True,0.000000,0.000000,NaN,global,76322.0,0.0,0.0,12664.0,8132.0,True,-0.442912,-0.357865,Medium,sector_account_category,462.0,-0.553581,0.753919,1040730.0,1038421.0,True,-0.002221,-0.002219,Medium,sector_account_category,7207.0,-0.022273,0.081042,9

In [8]:
financial_data_03_new_sample.to_csv("../output/samples/03_financial_change_labels_new_sample.csv", index=False)

## 04

In [3]:
financial_data_04 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/04_financial_transition_labels.csv")

C:\Users\86132\AppData\Local\Temp\ipykernel_24864\824491810.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  financial_data_04 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/04_financial_transition_labels.csv")

In [4]:
financial_data_04_sample = financial_data_04.sample(n=1000, random_state=42)

In [5]:
financial_data_04_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,period_t,period_t_plus_1,available_date_t,available_date_t_plus_1,gap_days,evidence_tier_t,evidence_tier_t_plus_1,negative_equity_transition_eligible,negative_equity_onset_eligible,negative_equity_recovery_eligible,negative_equity_persistent_eligible,negative_equity_onset_flag,negative_equity_recovery_flag,negative_equity_persistent_flag,working_capital_transition_eligible,working_capital_deficit_onset_eligible,working_capital_deficit_recovery_eligible,working_capital_deficit_persistent_eligible,working_capital_deficit_onset_flag,working_capital_deficit_recovery_flag,working_capital_deficit_persistent_flag,creditor_pressure_transition_eligible,creditor_pressure_onset_eligible,creditor_pressure_recovery_eligible,creditor_pressure_persistent_eligible,creditor_pressure_onset_flag,creditor_pressure_recovery_flag,creditor_pressure_persistent_flag,reported_loss_transition_eligible,reported_loss_onset_eligible,reported_loss_recovery_eligible,reported_loss_onset_flag,reported_loss_recovery_flag
64119,13955543,ALPHA UK INVESTMENTS LIMITED,Real Estate,TOTAL EXEMPTION FULL,2024-03-31,2025-03-31,2024-12-31,2026-01-31,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,True,False,True,True,NaN,False,True,True,False,True,True,NaN,False,True,False,False,False,False,NaN,NaN,NaN,False,False,False,NaN,NaN
68035,14390075,CR WENTWORTH PT LIMITED,"Technology, legal & professional",MICRO ENTITY,2024-09-26,2025-09-26,2025-12-31,2026-06-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,True,True,False,False,False,NaN,NaN,True,True,False,False,False,NaN,NaN,True,True,False,False,False,NaN,NaN,False,False,False,NaN,NaN
53647,12765519,MYLEE'S LTD,Wholesale & Retail,TOTAL EXEMPTION FULL,2024-07-31,2025-07-31,2025-04-30,2026-04-30,365.0,T2_balance_sheet_rich,T2_balance_sheet_rich,True,True,False,False,False,NaN,NaN,True,True,False,False,False,NaN,NaN,True,True,False,False,False,NaN,NaN,False,False,False,NaN,NaN
49880,12316478,SOUTH CUMBRIAN PROPERTIES LTD,Real Estate,MICRO ENTITY,2023-11-30,2024-11-30,2024-08-31,2025-09-30,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,True,True,False,False,False,NaN,NaN,True,True,False,False,False,NaN,NaN,True,False,True,True,NaN,False,True,False,False,False,NaN,NaN
13810,5962404,SAINT ANDREWS PROPERTIES LIMITED,Real Estate,TOTAL EXEMPTION FULL,2023-10-31,2024-10-31,2024-07-31,2025-07-31,366.0,T2_balance_sheet_rich,T2_balance_sheet_rich,True,True,False,False,False,NaN,NaN,True,False,True,True,NaN,False,True,False,False,False,False,NaN,NaN,NaN,True,True,False,False,NaN

In [6]:
financial_data_04_sample.to_csv("../output/samples/04_financial_transittion_labels_sample.csv", index=False)

## 05

In [8]:
financial_data_05 = pd.read_csv("../01 EDA + Data PreProcessing/04_Five_CSV/05_financial_data_quality_labels_100k.csv")

In [9]:
financial_data_05_sample = financial_data_05.sample(n=1000, random_state=42)

In [10]:
financial_data_05_sample.head()

,CompanyNumber_norm,CompanyName,primary_sector,Accounts_AccountCategory,latest_period_end,latest_available_date,financial_evidence_tier,available_core_proxy_field_count,available_any_financial_field_count,matched_account_periods,useful_financial_periods,first_period_end,turnover_periods,previous_gap_days,has_matched_accounts_flag,has_two_plus_financial_periods_flag,has_two_plus_turnover_periods_flag,has_any_turnover_flag,useful_financial_evidence_flag,core_fields_complete_flag,accounts_age_days_at_snapshot,accounts_older_than_24m_flag,impossible_negative_value_flag,impossible_negative_fields,extreme_amount_p999_flag,latest_period_gap_anomaly_flag,evidence_improved_flag,evidence_deteriorated_flag,extreme_amount_thresholds_json
75721,11153083,LARWIN ESTATES LTD,Real Estate,MICRO ENTITY,2024-01-31,2024-10-31,T2_balance_sheet_rich,5.0,6.0,1.0,1.0,2024-01-31,0.0,NaN,True,False,False,False,True,False,881.0,True,False,NaN,False,NaN,NaN,NaN,"{""cash"": 11132876.441001004, ""creditors_total""..."
80184,13431081,EMPORIUM OF WONDERS LIMITED,Wholesale & Retail,TOTAL EXEMPTION FULL,2025-06-30,2026-03-31,T2_balance_sheet_rich,6.0,6.0,2.0,2.0,2024-06-30,0.0,365.0,True,True,False,False,True,False,365.0,False,False,NaN,False,False,False,False,"{""cash"": 11132876.441001004, ""creditors_total""..."
19864,10472899,GREEN HOME ENERGY (PRIVATE) LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-03-31,2025-12-31,T2_balance_sheet_rich,5.0,5.0,2.0,2.0,2024-03-31,0.0,365.0,True,True,False,False,True,False,456.0,False,False,NaN,False,False,False,False,"{""cash"": 11132876.441001004, ""creditors_total""..."
76699,10800893,GROWTH GORILLA LTD,"Technology, legal & professional",TOTAL EXEMPTION FULL,2025-03-31,2026-01-31,T2_balance_sheet_rich,7.0,7.0,2.0,2.0,2024-03-31,0.0,365.0,True,True,False,False,True,True,456.0,False,False,NaN,False,False,False,False,"{""cash"": 11132876.441001004, ""creditors_total""..."
92991,11377376,VAQUOI LIMITED,"Technology, legal & professional",MICRO ENTITY,2025-05-31,2026-02-28,T2_balance_sheet_rich,4.0,4.0,2.0,2.0,2024-05-31,0.0,365.0,True,True,False,False,True,False,395.0,False,False,NaN,False,False,False,False,"{""cash"": 11132876.441001004, ""creditors_total""..."

In [12]:
financial_data_05_sample.to_csv("../output/samples/05_financial_data_quality_labels_sample.csv", index=False)

## hiring

In [ ]:
hiring_100k_path = Path(r"E:\files\Bristol\project\记录\data\hiring\hiring_100k.csv")
company_hiring_path = Path(r"E:\files\Bristol\project\记录\data\hiring\company_hiring_score.csv")

In [3]:
hiring_01 = pd.read_csv(hiring_100k_path)

In [4]:
hiring_01_sample = hiring_01.sample(n=1000, random_state=42)

In [5]:
hiring_01_sample.head()

,CompanyNumber,CompanyName,primary_sector,CompanyStatus,company_age_years,Accounts_AccountCategory,sector_hiring_score,status_factor,age_factor,scale_factor,filing_freshness_factor,financing_factor,adjustment_factor,company_hiring_score,hiring_signal_quality
75721,11153083,LARWIN ESTATES LTD,Real Estate,Active,8.4,MICRO ENTITY,23.4,1.0,1.00,0.85,0.50,0.85,0.36125,8.5,79.5
80184,13431081,EMPORIUM OF WONDERS LIMITED,Wholesale & Retail,Active,5.1,TOTAL EXEMPTION FULL,52.4,1.0,1.15,0.90,0.85,1.00,0.87975,46.1,78.9
19864,10472899,GREEN HOME ENERGY (PRIVATE) LIMITED,"Technology, legal & professional",Active,9.6,MICRO ENTITY,64.1,1.0,1.00,0.85,0.85,1.00,0.72250,46.3,91.8
76699,10800893,GROWTH GORILLA LTD,"Technology, legal & professional",Active,9.1,TOTAL EXEMPTION FULL,64.1,1.0,1.00,0.90,0.85,1.00,0.76500,49.0,91.8
92991,11377376,VAQUOI LIMITED,"Technology, legal & professional",Active,8.1,MICRO ENTITY,64.1,1.0,1.00,0.85,0.85,1.00,0.72250,46.3,91.8

In [6]:
hiring_01_sample.to_csv("../output/samples/hiring_100k_sample.csv", index=False)

### company hiring

In [7]:
hiring_02 = pd.read_csv(company_hiring_path)

C:\Users\86132\AppData\Local\Temp\ipykernel_21580\4242448751.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  hiring_02 = pd.read_csv(company_hiring_path)

In [11]:
hiring_02.shape

(3415689, 15)

In [8]:
hiring_02_sample = hiring_02.sample(n=1000, random_state=42)

In [9]:
hiring_02_sample.head()

,CompanyNumber,CompanyName,primary_sector,CompanyStatus,company_age_years,Accounts_AccountCategory,sector_hiring_score,status_factor,age_factor,scale_factor,filing_freshness_factor,financing_factor,adjustment_factor,company_hiring_score,hiring_signal_quality
2436424,15958424,SHEFFORD SWIM SCHOOL LIMITED,"Public sector, education & charities",Active,1.8,MICRO ENTITY,68.7,1.0,0.65,0.85,1.00,1.00,0.552500,38.0,89.7
2011331,14646234,12 GORE TERRACE LTD,Real Estate,Active,3.4,TOTAL EXEMPTION FULL,20.8,1.0,1.15,0.90,0.85,0.85,0.747787,15.6,73.6
2225587,15382322,FORESIGHT COMMON LTD,Real Estate,Active,2.5,MICRO ENTITY,20.8,1.0,0.80,0.85,0.85,0.95,0.549100,11.4,73.6
559156,7376902,LITTLE WEAVERS DAY NURSERY LIMITED,"Public sector, education & charities",Active,15.8,TOTAL EXEMPTION FULL,68.7,1.0,0.90,0.90,0.85,1.00,0.688500,47.3,89.7
2038068,14737885,IVCHI LTD,"Technology, legal & professional",Active,3.3,MICRO ENTITY,66.9,1.0,1.15,0.85,0.85,1.00,0.830875,55.6,90.1

In [10]:
hiring_02_sample.to_csv("../output/samples/company_hiring_score_sample.csv", index=False)

In [17]:
hiring_02_sample['sector_hiring_score'].unique()

array([68.7, 20.8, 66.9, 58. , 65.7, 72.4, 66.7, 44.9])

In [18]:
hiring_02_sample['hiring_signal_quality'].unique()

array([89.7, 73.6, 90.1, 80.6, 85.9, 78.3, 84.5])

## companies House

In [12]:
ch = pd.read_csv("../01 EDA + Data PreProcessing/01_CompaniesSelected/UKcompanies_active_account_category_sample_100k.csv")

In [13]:
ch_sample = ch.sample(n=1000, random_state=42)

In [14]:
ch_sample.head()

,CompanyNumber,CompanyName,CompanyStatus,CompanyCategory,CountryOfOrigin,RegAddress_Country,RegAddress_PostTown,RegAddress_PostCode,IncorporationDate,primary_sic_code,sic_codes_all,matched_sectors,has_fast_growth,multi_sic_company,primary_sector,sector_id,Accounts_AccountCategory,Accounts_LastMadeUpDate,Accounts_NextDueDate,Mortgages_NumMortOutstanding,Mortgages_NumMortCharges,has_outstanding_charges,company_age_years,CountryOfOrigin_clean,is_uk_company
75721,11153083,LARWIN ESTATES LTD,Active,Private Limited Company,United Kingdom,ENGLAND,HOUNSLOW,TW4 7QJ,2018-01-16,68100,"['68100', '68209']",['Real Estate'],False,True,Real Estate,4.0,MICRO ENTITY,2024-01-31,2025-10-31,4,5,True,8.4,united kingdom,True
80184,13431081,EMPORIUM OF WONDERS LIMITED,Active,Private Limited Company,United Kingdom,UNITED KINGDOM,BIRSTALL,WF17 9JX,2021-06-01,47910,['47910'],['Wholesale & Retail'],False,False,Wholesale & Retail,3.0,TOTAL EXEMPTION FULL,2025-06-30,2027-03-31,0,0,False,5.0,united kingdom,True
19864,10472899,GREEN HOME ENERGY (PRIVATE) LIMITED,Active,Private Limited Company,United Kingdom,ENGLAND,PINNER,HA5 4HP,2016-11-10,71122,['71122'],"['Technology, legal & professional']",False,False,"Technology, legal & professional",5.0,MICRO ENTITY,2025-03-31,2026-12-31,0,0,False,9.6,united kingdom,True
76699,10800893,GROWTH GORILLA LTD,Active,Private Limited Company,United Kingdom,UNITED KINGDOM,LONDON,EC2A 4NE,2017-06-02,73110,['73110'],"['Technology, legal & professional']",False,False,"Technology, legal & professional",5.0,TOTAL EXEMPTION FULL,2025-03-31,2026-12-31,0,0,False,9.0,united kingdom,True
92991,11377376,VAQUOI LIMITED,Active,Private Limited Company,United Kingdom,ENGLAND,LONDON,WC2A 2JR,2018-05-23,69201,['69201'],"['Technology, legal & professional']",False,False,"Technology, legal & professional",5.0,MICRO ENTITY,2025-05-31,2027-02-28,0,0,False,8.1,united kingdom,True

In [15]:
ch_sample.to_csv("../output/samples/UKcompaniesHouse_100k_sample.csv", index=False)